# .travis.yml

languge: node_js
node_js:
  - "6.11"

branches:
  only:
    - master

before_script:

scripts:
  - npm run build

after_success:
  - firebase deploy

notifications:
  email:
    on_failure: change
    on_success: change